-- LOGIN AS QLDE, chạy các lệnh bên dưới để tạo role--
CREATE ROLE ROLE_NV;
CREATE ROLE ROLE_GIAMDOC;
create role ROLE_NV_PHONG_NHANSU;
create role ROLE_NV_PHONG_KEHOACH;
create role ROLE_NV_PHONG_KINHDOANH;
create role ROLE_NV_PHONG_DEAN;
create role ROLE_TRUONG_PHONG;
create role ROLE_TRUONG_PHONG_DEAN;

-- ROLE NHÂN VIÊN
GRANT SELECT ON QLDA.NHANVIEN TO ROLE_NV;
GRANT UPDATE(HOTEN,PHAI,NGAYSINH,DIENTHOAI) on QLDA.NHANVIEN TO ROLE_NV;

-- ROLE PHÒNG NHÂN SỰ
GRANT select on QLDA.NHANVIEN TO ROLE_NV_PHONG_NHANSU;
GRANT update(LUONG,PHUCAP,MAPHONG) on QLDA.NHANVIEN TO ROLE_NV_PHONG_NHANSU;

GRANT SELECT ON QLDA.THAMGIADEAN TO ROLE_NV_PHONG_NHANSU;

-- ROLE NHÂN VIÊN PHÒNG ĐỀ ÁN
GRANT SELECT,UPDATE, INSERT, DELETE ON QLDA.THAMGIADEAN TO ROLE_NV_PHONG_DEAN;
GRANT SELECT ON QLDA.DEAN TO ROLE_NV_PHONG_DEAN;

-- ROLE NHÂN VIÊN PHÒNG KINH DOANH
GRANT SELECT ON QLDA.THAMGIADEAN TO ROLE_NV_PHONG_KINHDOANH;
GRANT SELECT ON QLDA.DEAN TO ROLE_NV_PHONG_KINHDOANH;

-- ROLE NHÂN VIÊN PHÒNG KẾ HOẠCH
GRANT SELECT,UPDATE, INSERT, DELETE ON QLDA.DEAN TO ROLE_NV_PHONG_KEHOACH;


-- ROLE TRƯỞNG PHÒNG
GRANT SELECT ON QLDA.NHANVIEN TO ROLE_TRUONG_PHONG;
GRANT SELECT ON QLDA.THAMGIADEAN TO ROLE_TRUONG_PHONG;
GRANT SELECT ON QLDA.DEAN TO ROLE_TRUONG_PHONG;
-- ROLE TRƯỞNG PHÒNG ĐỀ ÁN

GRANT SELECT ON QLDA.THAMGIADEAN TO ROLE_TRUONG_PHONG_DEAN;
GRANT UPDATE(THOIGIAN,TRANGTHAI) ON QLDA.THAMGIADEAN TO ROLE_TRUONG_PHONG_DEAN;

-- ROLE GIÁM ĐỐC
GRANT select on QLDA.NHANVIEN TO ROLE_GIAMDOC;
GRANT update(LUONG,PHUCAP,MAPHONG) on QLDA.NHANVIEN TO ROLE_GIAMDOC;
GRANT SELECT ON QLDA.THAMGIADEAN TO ROLE_GIAMDOC;
GRANT SELECT ON QLDA.DEAN TO ROLE_GIAMDOC;