select status from dba_ols_status where name = 'OLS_CONFIGURE_STATUS';
select value from v$option where parameter = 'Oracle Label Security';

-- unlock LBACSYS account
ALTER USER lbacsys IDENTIFIED BY lbacsys ACCOUNT UNLOCK;
-- login LBACSYS tạo chính sách, 
EXEC SA_SYSDBA.CREATE_POLICY (policy_name => 'OLS_NHANVIEN',column_name => 'OLS_COLUMN');

-- Tạo level cho chính sách
EXEC SA_COMPONENTS.CREATE_LEVEL('OLS_NHANVIEN',10,'TT','THÔNG THƯỜNG');
EXEC SA_COMPONENTS.CREATE_LEVEL('OLS_NHANVIEN',20,'TP','TRƯỞNG PHÒNG');
EXEC SA_COMPONENTS.CREATE_LEVEL('OLS_NHANVIEN',30,'GD','GIAMDOC');

-- Tạo nhãn
EXEC SA_LABEL_ADMIN.CREATE_LABEL('OLS_NHANVIEN', 10, 'TT');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('OLS_NHANVIEN', 20, 'TP');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('OLS_NHANVIEN', 30, 'GD');

-- GÁN CHÍNH SÁCH OLS LÊN BẢNG DỰ ÁN
EXEC SA_POLICY_ADMIN.APPLY_TABLE_POLICY('OLS_NHANVIEN', 'QLDA', 'NHANVIEN', 'NO_CONTROL');

-- GÁN LEVEL CHO USER NHÂN VIÊN
EXEC SA_USER_ADMIN.SET_LEVELS ('OLS_NHANVIEN', 'NV100', 'GD');
EXEC SA_USER_ADMIN.SET_LEVELS ('OLS_NHANVIEN', 'NV101', 'TP');
EXEC SA_USER_ADMIN.SET_LEVELS ('OLS_NHANVIEN', 'NV106', 'TP');
EXEC SA_USER_ADMIN.SET_LEVELS ('OLS_NHANVIEN', 'NV111', 'TP');
EXEC SA_USER_ADMIN.SET_LEVELS ('OLS_NHANVIEN', 'NV116', 'TP');
EXEC SA_USER_ADMIN.SET_LEVELS ('OLS_NHANVIEN', 'NV101', LABEL_TO_CHAR(20));
EXEC SA_USER_ADMIN.SET_LEVELS ('OLS_NHANVIEN', 'NV101', LABEL_TO_CHAR(20));
exec SA_USER_ADMIN.SET_LEVELS('OLS_NHANVIEN', 'NV101', LABEL_TO_CHAR(20));

create or replace procedure set_label (label_value int, user_name in varchar2)
as
  TEMP varchar2(200);
begin
    EXEC SA_USER_ADMIN.SET_LEVELS('OLS_NHANVIEN', user_name, LABEL_TO_CHAR(label_value));
end




-- GÁN QUYỀN SELECT,UPDATE QLDA.NHANVIEN CHO lbacsys 
grant select,update on QLDA.NHANVIEN to lbacsys;

-- CẬP NHẬT NHÃN CHO BẢNG NHÂN VIÊN
UPDATE QLDA.NHANVIEN SET OLS_COLUMN = 10;
UPDATE QLDA.NHANVIEN SET OLS_COLUMN = 20 WHERE MANV='NV101';
UPDATE QLDA.NHANVIEN SET OLS_COLUMN = 20 WHERE MANV='NV106';
UPDATE QLDA.NHANVIEN SET OLS_COLUMN = 20 WHERE MANV='NV111';
UPDATE QLDA.NHANVIEN SET OLS_COLUMN = 20 WHERE MANV='NV116';
UPDATE QLDA.NHANVIEN SET OLS_COLUMN = 30 WHERE MANV='NV100';

-- KÍCH HOẠT CHÍNH SÁCH OLS
EXEC SA_POLICY_ADMIN.DISABLE_TABLE_POLICY('OLS_NHANVIEN', 'QLDA', 'NHANVIEN');
EXEC SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('OLS_NHANVIEN', 'QLDA', 'NHANVIEN');
EXEC SA_POLICY_ADMIN.APPLY_TABLE_POLICY('OLS_NHANVIEN', 'QLDA', 'NHANVIEN', 'READ_CONTROL');

-- Cấp quyền gán nhãn cho QLDA
GRANT OLS_NHANVIEN_DBA TO QLDA;

SELECT sa_session.read_label('OLS_NHANVIEN') From DUAL;
select * from qlda.nhanvien


