/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Entity.Nhanvien;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Kuga
 */
public class Main_AD extends javax.swing.JFrame {

    Connection con;
    public Connection getCon() {
        return con;
    }

    public void setCon(Connection con) {
        this.con = con;
    }
    public Main_AD(Connection con) {
        initComponents();
        setCon(con);
        setLocationRelativeTo(null);
        setTitle("QUẢN LÝ DỰ ÁN");
        setResizable(false);
        loadUserName();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e) {
                    int hoi = JOptionPane.showConfirmDialog(null, "Bạn dang thao tác, xác nhận thoát (Yes)?",
                            "Cảnh Báo", JOptionPane.YES_NO_OPTION);
                    if (hoi == JOptionPane.YES_OPTION) {
                        try {
                            con.close();
                        } catch (SQLException ex) {
                            Logger.getLogger(Main_Admin.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        System.exit(0);
                    }
                }
        });
        dateNgaySinh.setDate(Calendar.getInstance().getTime());
    }
    public Main_AD() {
        initComponents();
        setTitle("QUẢN LÝ DỰ ÁN");
        setLocationRelativeTo(null);
        setResizable(false);
                dateNgaySinh.setDate(Calendar.getInstance().getTime());
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void loadUserName()
    {
        DefaultComboBoxModel dcbmodel_NV=new DefaultComboBoxModel();
        dcbmodel_NV.addElement("-----");
        // load các user/nv có mã bắt đầu là NV
        String strGet = "select username from DBA_users where username like 'NV%' order by username";
        try {
            PreparedStatement pstmt = con.prepareStatement(strGet);
            ResultSet rs = pstmt.executeQuery();
            if(rs!=null){
                while (rs.next()) {                    
                    dcbmodel_NV.addElement(rs.getString("username"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        cbbNhanVien.setModel(dcbmodel_NV);
    }
    public void loadRolePrivs2(String roleName)
    {
        Vector clums = new Vector();
        clums.add("Tên bảng");
        clums.add("Tên cột");
        clums.add("Quyền hạn");
        Vector data = new Vector();
        String strGet = "SELECT TABLE_NAME,COLUMN_NAME,PRIVILEGE FROM ROLE_TAB_PRIVS WHERE ROLE LIKE ? ORDER BY TABLE_NAME,COLUMN_NAME,PRIVILEGE";
        try {
                PreparedStatement pstmt = con.prepareStatement(strGet);
                pstmt.setString(1, roleName);
                ResultSet rs = pstmt.executeQuery();
                if(rs!=null){
                    while (rs.next()) {
                        Vector row = new Vector();
                        row.add(rs.getString(1));
                        row.add(rs.getString(2));
                        row.add(rs.getString(3));
                        data.add(row);
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
        }
        DefaultTableModel dtm_Role= new DefaultTableModel(data, clums);
        tableRole2.setModel(dtm_Role);
    }
    
    public void loadRolePrivs1(String nameRole)
    {
        Vector clums = new Vector();
        clums.add("Tên bảng");
        clums.add("Tên cột");
        clums.add("Quyền hạn");
        Vector data = new Vector();

        String strGet= "select table_name,column_name,privilege from Role_tab_privs where role like ? order by table_name,column_name,privilege";
        try {
            PreparedStatement pstmt = con.prepareStatement(strGet);
            pstmt.setString(1, nameRole);
            ResultSet rs = pstmt.executeQuery();
            if(rs!=null){
                while (rs.next()) {
                    Vector row = new Vector();
                    row.add(rs.getString(1));
                    row.add(rs.getString(2));
                    row.add(rs.getString(3));
                    data.add(row);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        DefaultTableModel dtm_Role= new DefaultTableModel(data, clums);
        tableRole1.setModel(dtm_Role);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        pnThemNV = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfMaNV = new javax.swing.JTextField();
        tfHoTen = new javax.swing.JTextField();
        tfSDT = new javax.swing.JTextField();
        tfLuong = new javax.swing.JTextField();
        tfPhuCap = new javax.swing.JTextField();
        cbbPhai = new javax.swing.JComboBox<>();
        cbbCapBac = new javax.swing.JComboBox<>();
        cbbPhong = new javax.swing.JComboBox<>();
        btnThemNV = new javax.swing.JButton();
        dateNgaySinh = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cbbNhanVien = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listRoleCoSan = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listRoleDuocCap = new javax.swing.JList<>();
        btnCapRole = new javax.swing.JButton();
        btnThuRole = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableRole1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        btnCapNhatNV = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tfNhanNV = new javax.swing.JTextField();
        btnCapNhatNhan = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        tfNewRole = new javax.swing.JTextField();
        btnThemRole = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        cbbListRole = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cbbListTable = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cbbListPrivs = new javax.swing.JComboBox<>();
        btnPhanQuyenRole = new javax.swing.JButton();
        btnLayThongTin = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableRole2 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        cbbListColumn = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnLoadNV = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableNV = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePrivs = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane6.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHÀO XẾP, CHÚC XẾP MỘT NGÀY TỐT LÀNH");

        pnThemNV.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thêm nhân viên mới"));
        pnThemNV.setPreferredSize(new java.awt.Dimension(800, 200));

        jLabel2.setText("Mã NV:");

        jLabel3.setText("Họ tên:");

        jLabel4.setText("Ngày sinh:");

        jLabel5.setText("SĐT:");

        jLabel6.setText("Lương:");

        jLabel7.setText("Phụ cấp:");

        jLabel8.setText("Phòng:");

        jLabel9.setText("Cấp bậc:");

        tfMaNV.setToolTipText("Mã dạng NV1xx");

        tfHoTen.setText("Tủm");
        tfHoTen.setToolTipText("Họ tên của nhân viên");
        tfHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHoTenActionPerformed(evt);
            }
        });

        tfSDT.setText("1234567980");
        tfSDT.setToolTipText("SĐT của nhân viên");

        tfLuong.setText("500");
        tfLuong.setToolTipText("Lương cơ bản");
        tfLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLuongActionPerformed(evt);
            }
        });

        tfPhuCap.setText("50");
        tfPhuCap.setToolTipText("Lương phụ cấp");

        cbbPhai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbbPhai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbPhaiActionPerformed(evt);
            }
        });

        cbbCapBac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2" }));
        cbbCapBac.setToolTipText("0(NV Thường); \n1(Giám đốc); \n2(Trưởng phòng)");

        cbbPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PB001", "PB002", "PB003", "PB004" }));
        cbbPhong.setToolTipText("PB001( Nhân Sự); \nPB002(Kế Hoạch); \nPB003(Đề Án); \nPB004( Kinh Doanh)"); // NOI18N
        cbbPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbPhongActionPerformed(evt);
            }
        });

        btnThemNV.setText("Thêm nhân viên");
        btnThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNVActionPerformed(evt);
            }
        });

        dateNgaySinh.setDateFormatString("dd/MM/yyyy");

        jLabel11.setText("Phái:");

        javax.swing.GroupLayout pnThemNVLayout = new javax.swing.GroupLayout(pnThemNV);
        pnThemNV.setLayout(pnThemNVLayout);
        pnThemNVLayout.setHorizontalGroup(
            pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfMaNV)
                    .addComponent(cbbPhai, 0, 89, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThemNVLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnThemNVLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnThemNVLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbPhong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnThemNVLayout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbCapBac, 0, 97, Short.MAX_VALUE)
                    .addComponent(tfLuong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnThemNVLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnThemNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnThemNVLayout.setVerticalGroup(
            pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemNVLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(tfMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(3, 3, 3)
                .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbPhai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cbbPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(cbbCapBac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThemNV)))
                .addGap(19, 19, 19))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Phân quyền"));

        cbbNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "NV101", "NV102", "NV103" }));
        cbbNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNhanVienActionPerformed(evt);
            }
        });

        listRoleCoSan.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listRoleCoSanValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listRoleCoSan);

        jLabel12.setText("Danh sách role sẳn có:");

        jLabel13.setText("Danh sách role được gán:");

        listRoleDuocCap.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listRoleDuocCapValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listRoleDuocCap);

        btnCapRole.setText(">>");
        btnCapRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapRoleActionPerformed(evt);
            }
        });

        btnThuRole.setText("<<");
        btnThuRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuRoleActionPerformed(evt);
            }
        });

        tableRole1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên bảng", "Tên cột", "Quyền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableRole1);

        jLabel14.setText("Quyền role trên bảng:");

        btnCapNhatNV.setText("Lấy danh sách");
        btnCapNhatNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatNVActionPerformed(evt);
            }
        });

        jLabel10.setText("Giá trị nhãn:");

        tfNhanNV.setText("0");

        btnCapNhatNhan.setText("Cập nhật nhãn");
        btnCapNhatNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbNhanVien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCapNhatNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCapNhatNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNhanNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCapRole)
                                    .addComponent(btnThuRole)))
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnCapRole)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnThuRole)
                                .addGap(15, 15, 15))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCapNhatNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfNhanNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCapNhatNhan)))
                .addGap(7, 7, 7)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pnThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("QL Nhân Viên", jPanel1);

        jLabel16.setText("Tên role:");

        tfNewRole.setText("ROLE_");

        btnThemRole.setText("Thêm Role");
        btnThemRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemRoleActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Phân quyền cho role"));

        cbbListRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbListRoleActionPerformed(evt);
            }
        });

        jLabel17.setText("Tên role:");

        jLabel18.setText("Tên Bảng:");

        cbbListTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbListTableActionPerformed(evt);
            }
        });

        jLabel19.setText("Quyền:");

        cbbListPrivs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Insert", "Select", "Update", "Delete" }));

        btnPhanQuyenRole.setText("Phân quyền");
        btnPhanQuyenRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhanQuyenRoleActionPerformed(evt);
            }
        });

        btnLayThongTin.setText("Load dữ liệu");
        btnLayThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayThongTinActionPerformed(evt);
            }
        });

        tableRole2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên bảng", "Tên cột", "Quyền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tableRole2);

        jLabel20.setText("Tên cột:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnLayThongTin)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbListRole, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbListTable, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel20))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(cbbListPrivs, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbbListColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPhanQuyenRole)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(7, 7, 7)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbListRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbListTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLayThongTin)
                    .addComponent(cbbListColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbListPrivs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPhanQuyenRole))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNewRole, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnThemRole)
                        .addGap(0, 596, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfNewRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemRole))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("QL Role", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1005, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("QL Table", jPanel6);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Xem nhân viên"));

        btnLoadNV.setText("Lấy DS NV");
        btnLoadNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadNVActionPerformed(evt);
            }
        });

        tableNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Họ tên", "Phòng ban", "Cấp bậc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNVMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tableNV);

        tablePrivs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Tên bảng", "Tên Cột", "Quyền hạn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablePrivs);

        jLabel15.setText("Các quyền mức cột của nhân viên:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLoadNV)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLoadNV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Nhân viên", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1009, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void tfHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHoTenActionPerformed

    private void tfLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLuongActionPerformed

    private void cbbPhaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbPhaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbPhaiActionPerformed

    private void cbbPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbPhongActionPerformed

    private void btnThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNVActionPerformed
        Nhanvien nv= new Nhanvien();
        nv.setMaNV(tfMaNV.getText().toUpperCase());
        nv.setHoTen(tfHoTen.getText());
        nv.setSdt(tfSDT.getText());

        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        String dateFormat = formatter.format(dateNgaySinh.getDate());
        nv.setNgaySinh(dateFormat);

        nv.setPhongBan(cbbPhong.getSelectedItem().toString());
        nv.setPhai(cbbPhai.getSelectedItem().toString());
        nv.setLuong(tfLuong.getText());
        nv.setPhuCap(tfPhuCap.getText());
        nv.setCapBac(cbbCapBac.getSelectedItem().toString());
        System.out.println(nv.toString());
        String strGet = "select * from QLDA.NHANVIEN where MANV like ?";
        try {
            PreparedStatement pstmt = con.prepareStatement(strGet);
            pstmt.setString(1, nv.getMaNV());
            ResultSet rs = pstmt.executeQuery();
            if(rs!=null){
                // kiểm tra MANV đã tồn tại
                while (rs.next()) {
                    JOptionPane.showMessageDialog(null, "MANV đã tồn tại!.","Thông báo",1);
                    tfMaNV.requestFocus();
                    return;
                }
            }
            strGet ="insert into QLDA.NHANVIEN (MANV,HOTEN,PHAI,NGAYSINH,DIENTHOAI,LUONG,PHUCAP,MAPHONG,CAPBAC)VALUES "
            + "('"+nv.getMaNV()+"','"
            + nv.getHoTen()+"','"
            + nv.getPhai()+"',"
            + "TO_DATE('"+nv.getNgaySinh()+"','DD/MM/YYYY')"+",'"
            + nv.getSdt()+"','"
            + nv.getLuong()+"','"
            + nv.getPhuCap()+"','"
            + nv.getPhongBan()+"','"
            + nv.getCapBac()+"')";
            System.out.println(strGet);

            pstmt = con.prepareStatement(strGet);
            pstmt.executeUpdate();

            strGet="CREATE USER "+nv.getMaNV()+" IDENTIFIED BY "+nv.getMaNV();
            System.out.println(strGet);
            pstmt = con.prepareStatement(strGet);
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Thêm NV thành công, vui lòng cấp role.","Thông báo",1);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Xảy ra lỗi khi kết nối CSDL.","Thông báo",1);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemNVActionPerformed

    private void cbbNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNhanVienActionPerformed
        // TODO add your handling code here:
        DefaultListModel dlm_RoleCoSan= new DefaultListModel();
        DefaultListModel dlm_RoleDuocCap= new DefaultListModel();

        String selectedNV= cbbNhanVien.getSelectedItem().toString();
        if(selectedNV=="-----"){
            listRoleCoSan.setModel(dlm_RoleCoSan);
            listRoleDuocCap.setModel(dlm_RoleDuocCap);
            Vector clums = new Vector();
            clums.add("Tên bảng");
            clums.add("Chủ sở hữu");
            clums.add("Quyền");
            Vector data = new Vector();
            DefaultTableModel dtm_Role = new DefaultTableModel(data, clums);
            tableRole1.setModel(dtm_Role);
            return;
        }

        String strGet = "select ROLE from Dba_roles where ROLE like 'ROLE%' and ROLE not in (select granted_role from Dba_role_privs where grantee like ?)order by ROLE";
        try {
            PreparedStatement pstmt = con.prepareStatement(strGet);
            pstmt.setString(1, selectedNV);
            ResultSet rs = pstmt.executeQuery();
            if(rs!=null){
                while (rs.next()) {
                    dlm_RoleCoSan.addElement(rs.getString("ROLE"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        listRoleCoSan.setModel(dlm_RoleCoSan);

        strGet = "select granted_role from Dba_role_privs where grantee like ? order by granted_role";
        try {
            PreparedStatement pstmt = con.prepareStatement(strGet);
            pstmt.setString(1, selectedNV);
            ResultSet rs = pstmt.executeQuery();
            if(rs!=null){
                while (rs.next()) {
                    dlm_RoleDuocCap.addElement(rs.getString("granted_role"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        listRoleDuocCap.setModel(dlm_RoleDuocCap);
        
        strGet = "select OLS_COLUMN from NHANVIEN where MANV like ?";
        try {
            PreparedStatement pstmt = con.prepareStatement(strGet);
            pstmt.setString(1, selectedNV);
            ResultSet rs = pstmt.executeQuery();
            if(rs!=null){
                while (rs.next()) {
                    tfNhanNV.setText(rs.getString(1));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_cbbNhanVienActionPerformed

    private void listRoleCoSanValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listRoleCoSanValueChanged
        // TODO add your handling code here:
        String value = listRoleCoSan.getSelectedValue();
        if(value != null)
        {
            loadRolePrivs1(value);
        }
    }//GEN-LAST:event_listRoleCoSanValueChanged

    private void listRoleDuocCapValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listRoleDuocCapValueChanged
        // TODO add your handling code here:
        String value= listRoleDuocCap.getSelectedValue();
        if(value != null)
        {
            loadRolePrivs1(value);
        }
    }//GEN-LAST:event_listRoleDuocCapValueChanged

    private void btnCapRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapRoleActionPerformed
        // TODO add your handling code here:
        String value=listRoleCoSan.getSelectedValue();
        String username=cbbNhanVien.getSelectedItem().toString();
        if(value !=null && username !=null)
        {
            int index=listRoleCoSan.getSelectedIndex();

            DefaultListModel model1 = (DefaultListModel) listRoleCoSan.getModel();
            model1.remove(index);
            listRoleCoSan.setModel(model1);

            // gọi oracle cấp role
            String strGet = "grant " + value + " to " + username;
            try {
                // cấp role
                System.out.println(strGet);
                PreparedStatement pstmt = con.prepareStatement(strGet);
                ResultSet rs = pstmt.executeQuery();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Xảy ra lỗi truy vấn CSDL, vui lòng thử lại","Thông báo",1);
                e.printStackTrace();
                return;
            }

            DefaultListModel model2 = (DefaultListModel) listRoleDuocCap.getModel();
            model2.addElement(value);
            listRoleDuocCap.setModel(model2);

            JOptionPane.showMessageDialog(null, "Cấp role thành công","Thông báo",1);
        }
    }//GEN-LAST:event_btnCapRoleActionPerformed

    private void btnThuRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuRoleActionPerformed
        // TODO add your handling code here:
        String value=listRoleDuocCap.getSelectedValue();
        String username=cbbNhanVien.getSelectedItem().toString();
        if(value !=null && username!=null)
        {
            int index=listRoleDuocCap.getSelectedIndex();
            DefaultListModel model1 = (DefaultListModel) listRoleDuocCap.getModel();
            model1.remove(index);
            listRoleDuocCap.setModel(model1);

            // gọi oracle thu role
            String strGet = "revoke " + value + " from " + username;
            try {
                // thu ROLE đã cấp
                System.out.println(strGet);
                PreparedStatement pstmt = con.prepareStatement(strGet);
                ResultSet rs = pstmt.executeQuery();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Xảy ra lỗi truy vấn CSDL, vui lòng thử lại","Thông báo",1);
                e.printStackTrace();
                return;
            }

            DefaultListModel model2 = (DefaultListModel) listRoleCoSan.getModel();
            model2.addElement(value);
            listRoleCoSan.setModel(model2);

            JOptionPane.showMessageDialog(null, "Thu hồi role thành công","Thông báo",1);
        }
    }//GEN-LAST:event_btnThuRoleActionPerformed

    private void btnCapNhatNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatNVActionPerformed
        // TODO add your handling code here:
        loadUserName();
    }//GEN-LAST:event_btnCapNhatNVActionPerformed

    private void btnLoadNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadNVActionPerformed
        // TODO add your handling code here:
        Vector clums = new Vector();
        clums.add("Mã NV");
        clums.add("Họ tên");
        clums.add("Phòng ban");
        clums.add("Cấp bậc");
        Vector data = new Vector();

        String strGet;
        strGet = "select MANV,HOTEN,MAPHONG,CAPBAC from QLDA.NHANVIEN";
        try {
            PreparedStatement pstmt = con.prepareStatement(strGet);
            ResultSet rs = pstmt.executeQuery();
            if(rs!=null){
                while (rs.next()) {
                    Vector row = new Vector();
                    row.add(rs.getString(1));
                    row.add(rs.getString(2));
                    row.add(rs.getString(3));
                    row.add(rs.getString(4));
                    data.add(row);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Có lỗi xảy ra!.","Thông báo",1);
            e.printStackTrace();
        }
        DefaultTableModel dtm_Role= new DefaultTableModel(data, clums);
        tableNV.setModel(dtm_Role);
    }//GEN-LAST:event_btnLoadNVActionPerformed

    private void tableNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNVMouseClicked
        // TODO add your handling code here:
        Vector clums = new Vector();
        clums.add("Mã NV");
        clums.add("Tên bảng");
        clums.add("Tên cột");
        clums.add("Quyền hạn");
        Vector data = new Vector();

        String strGet;
        int index= tableNV.getSelectedRow();
        if(index >0)
        {

            String manv=tableNV.getValueAt(index, 0).toString();
            strGet = "select distinct grantee,table_name,column_name,privilege "
                    + "from Role_tab_privs,Dba_role_privs "
                    + "where granted_role like ROLE and grantee like ? order by table_name,column_name,privilege ASC";
            try {
                PreparedStatement pstmt = con.prepareStatement(strGet);
                pstmt.setString(1, manv);
                ResultSet rs = pstmt.executeQuery();
                if(rs!=null){
                    while (rs.next()) {
                        Vector row = new Vector();
                        row.add(rs.getString(1));
                        row.add(rs.getString(2));
                        row.add(rs.getString(3));
                        row.add(rs.getString(4));
                        data.add(row);
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            DefaultTableModel dtm_Privs= new DefaultTableModel(data, clums);
            tablePrivs.setModel(dtm_Privs);
        }
    }//GEN-LAST:event_tableNVMouseClicked

    private void btnCapNhatNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatNhanActionPerformed
        // TODO add your handling code here:
        String selectedNV= cbbNhanVien.getSelectedItem().toString();
        int label = Integer.valueOf(tfNhanNV.getText());
        try {
            String strGet ="{CALL SA_USER_ADMIN.SET_LEVELS ('OLS_NHANVIEN', '"
                    + selectedNV + "', LABEL_TO_CHAR("
                    + label +"))}";
            System.out.println(strGet);
            PreparedStatement pstmt = con.prepareCall(strGet);
            pstmt.execute();
            JOptionPane.showMessageDialog(null, "Cập nhật nhãn thành công.","Thông báo",1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Xảy ra lỗi khi kết nối CSDL.","Thông báo",1);
            e.printStackTrace();
        } 
    }//GEN-LAST:event_btnCapNhatNhanActionPerformed

    private void btnThemRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemRoleActionPerformed
        // TODO add your handling code here:
        if(!tfNewRole.getText().toUpperCase().startsWith("NV")){
            JOptionPane.showMessageDialog(null, "Tên role phải bắt đầu là ROLE_.","Thông báo",1);
            return;
        }
        try {
            String strGet ="create role "+tfNewRole.getText();
            System.out.println(strGet);
            PreparedStatement pstmt = con.prepareStatement(strGet);
            pstmt.execute();
            JOptionPane.showMessageDialog(null, "Thêm role thành công.","Thông báo",1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Xảy ra lỗi khi kết nối CSDL.","Thông báo",1);
            e.printStackTrace();
        } 
    }//GEN-LAST:event_btnThemRoleActionPerformed

    private void btnLayThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayThongTinActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel dcbm_Role= new DefaultComboBoxModel();
        DefaultComboBoxModel dcbm_Table= new DefaultComboBoxModel();
        try {
            String strGet ="select Role from Dba_roles where ROLE like 'ROLE_%'";
            System.out.println(strGet);
            PreparedStatement pstmt = con.prepareStatement(strGet);
            ResultSet rs = pstmt.executeQuery();
            if(rs!=null){
                    while (rs.next()) {
                        dcbm_Role.addElement(rs.getString(1));
                    }
                }
            
            strGet ="select distinct table_name from user_tab_columns";
            System.out.println(strGet);
            pstmt = con.prepareStatement(strGet);
            rs = pstmt.executeQuery();
            if(rs!=null){
                    while (rs.next()) {
                        dcbm_Table.addElement(rs.getString(1));
                    }
                }
            cbbListRole.setModel(dcbm_Role);
            cbbListTable.setModel(dcbm_Table);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Xảy ra lỗi khi kết nối CSDL.","Thông báo",1);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLayThongTinActionPerformed

    private void cbbListRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbListRoleActionPerformed
        // TODO add your handling code here:
        int index = cbbListRole.getSelectedIndex();
        if (index>=0)
        {
            String roleName= cbbListRole.getItemAt(index);
            System.out.println(roleName);
            loadRolePrivs2(roleName);
        }
    }//GEN-LAST:event_cbbListRoleActionPerformed

    private void btnPhanQuyenRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhanQuyenRoleActionPerformed
        // TODO add your handling code here:
        int indexRole = cbbListRole.getSelectedIndex();
        int indexTable = cbbListTable.getSelectedIndex();
        int indexColumn = cbbListColumn.getSelectedIndex();
        int indexPrivs = cbbListPrivs.getSelectedIndex();
        if (indexRole>=0 && indexTable>=0 && indexPrivs>=0 && indexColumn>=0)
        {
            String roleName= cbbListRole.getItemAt(indexRole);
            String tableName= cbbListTable.getItemAt(indexTable);
            String columnName= cbbListColumn.getItemAt(indexColumn);
            String privsName= cbbListPrivs.getItemAt(indexPrivs);
            String strGet ;
            if(privsName.toUpperCase().equals("INSERT") || privsName.toUpperCase().equals("UPDATE"))
            {
                strGet = "grant "+privsName+"("+ columnName +") on " + tableName + " to " + roleName;
            }
            else
            {
                strGet = "grant "+privsName+" on " + tableName + " to " + roleName;
            }
            System.out.println(strGet);
            try {
                    PreparedStatement pstmt = con.prepareStatement(strGet);
                    pstmt.executeUpdate();
                } catch (Exception e) {
                    e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnPhanQuyenRoleActionPerformed

    private void cbbListTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbListTableActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel dcbm_column= new DefaultComboBoxModel();
        int indexTable = cbbListTable.getSelectedIndex();
        if ( indexTable>=0)
        {
            String tableName= cbbListTable.getItemAt(indexTable);
            String strGet = "select column_name from user_tab_columns where table_name like '" +tableName+ "'";
            System.out.println(strGet);
            try {
                    PreparedStatement pstmt = con.prepareStatement(strGet);
                    ResultSet rs = pstmt.executeQuery();
            if(rs!=null){
                    while (rs.next()) {
                        dcbm_column.addElement(rs.getString(1));
                    }
                }
                } catch (Exception e) {
                    e.printStackTrace();
            }
            cbbListColumn.setModel(dcbm_column);
        }
    }//GEN-LAST:event_cbbListTableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_AD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_AD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_AD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_AD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_AD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatNV;
    private javax.swing.JButton btnCapNhatNhan;
    private javax.swing.JButton btnCapRole;
    private javax.swing.JButton btnLayThongTin;
    private javax.swing.JButton btnLoadNV;
    private javax.swing.JButton btnPhanQuyenRole;
    private javax.swing.JButton btnThemNV;
    private javax.swing.JButton btnThemRole;
    private javax.swing.JButton btnThuRole;
    private javax.swing.JComboBox<String> cbbCapBac;
    private javax.swing.JComboBox<String> cbbListColumn;
    private javax.swing.JComboBox<String> cbbListPrivs;
    private javax.swing.JComboBox<String> cbbListRole;
    private javax.swing.JComboBox<String> cbbListTable;
    private javax.swing.JComboBox<String> cbbNhanVien;
    private javax.swing.JComboBox<String> cbbPhai;
    private javax.swing.JComboBox<String> cbbPhong;
    private com.toedter.calendar.JDateChooser dateNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JList<String> listRoleCoSan;
    private javax.swing.JList<String> listRoleDuocCap;
    private javax.swing.JPanel pnThemNV;
    private javax.swing.JTable tableNV;
    private javax.swing.JTable tablePrivs;
    private javax.swing.JTable tableRole1;
    private javax.swing.JTable tableRole2;
    private javax.swing.JTextField tfHoTen;
    private javax.swing.JTextField tfLuong;
    private javax.swing.JTextField tfMaNV;
    private javax.swing.JTextField tfNewRole;
    private javax.swing.JTextField tfNhanNV;
    private javax.swing.JTextField tfPhuCap;
    private javax.swing.JTextField tfSDT;
    // End of variables declaration//GEN-END:variables
}
