/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entity.Nhanvien;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kuga
 */
public class Main_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    Connection con;

    public Connection getCon() {
        return con;
    }

    public void setCon(Connection con) {
        this.con = con;
    }
    
    public Main_Admin(Connection con) {
        initComponents();
        setCon(con);
        setLocationRelativeTo(null);
        setTitle("QUẢN LÝ DỰ ÁN");
        setResizable(false);
        dateNgaySinh.setDate(Calendar.getInstance().getTime());
        loadUserName();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e) {
                    int hoi = JOptionPane.showConfirmDialog(null, "Bạn dang thao tác, xác nhận thoát (Yes)?",
                            "Cảnh Báo", JOptionPane.YES_NO_OPTION);
                    if (hoi == JOptionPane.YES_OPTION) {
                        try {
                            con.close();
                        } catch (SQLException ex) {
                            Logger.getLogger(Main_Admin.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        System.exit(0);
                    }
                }
        });
    }
    public Main_Admin() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("QUẢN LÝ DỰ ÁN");
        setResizable(false);
        dateNgaySinh.setDate(Calendar.getInstance().getTime());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnHello = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnScroll = new javax.swing.JPanel();
        pnThemNV = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfMaNV = new javax.swing.JTextField();
        tfHoTen = new javax.swing.JTextField();
        tfSDT = new javax.swing.JTextField();
        tfLuong = new javax.swing.JTextField();
        tfPhuCap = new javax.swing.JTextField();
        cbbPhai = new javax.swing.JComboBox<>();
        cbbCapBac = new javax.swing.JComboBox<>();
        cbbPhong = new javax.swing.JComboBox<>();
        btnThemNV = new javax.swing.JButton();
        dateNgaySinh = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbbNhanVien = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listRoleCoSan = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listRoleDuocCap = new javax.swing.JList<>();
        btnCapRole = new javax.swing.JButton();
        btnThuRole = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableRole = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        btnCapNhatNV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHÀO XẾP, CHÚC XẾP MỘT NGÀY TỐT LÀNH");

        javax.swing.GroupLayout pnHelloLayout = new javax.swing.GroupLayout(pnHello);
        pnHello.setLayout(pnHelloLayout);
        pnHelloLayout.setHorizontalGroup(
            pnHelloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnHelloLayout.setVerticalGroup(
            pnHelloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHelloLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnScroll.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnThemNV.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thêm nhân viên mới"));
        pnThemNV.setPreferredSize(new java.awt.Dimension(800, 200));

        jLabel2.setText("Mã NV:");

        jLabel3.setText("Họ tên:");

        jLabel4.setText("Ngày sinh:");

        jLabel5.setText("SĐT:");

        jLabel6.setText("Lương:");

        jLabel7.setText("Phụ cấp:");

        jLabel8.setText("Phòng:");

        jLabel9.setText("Cấp bậc:");

        tfMaNV.setToolTipText("Mã dạng NV1xx");

        tfHoTen.setText("Tủm");
        tfHoTen.setToolTipText("Họ tên của nhân viên");
        tfHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHoTenActionPerformed(evt);
            }
        });

        tfSDT.setText("1234567980");
        tfSDT.setToolTipText("SĐT của nhân viên");

        tfLuong.setText("500");
        tfLuong.setToolTipText("Lương cơ bản");
        tfLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLuongActionPerformed(evt);
            }
        });

        tfPhuCap.setText("50");
        tfPhuCap.setToolTipText("Lương phụ cấp");

        cbbPhai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbbPhai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbPhaiActionPerformed(evt);
            }
        });

        cbbCapBac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2" }));
        cbbCapBac.setToolTipText("0(NV Thường); \n1(Giám đốc); \n2(Trưởng phòng)");

        cbbPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PB001", "PB002", "PB003", "PB004" }));
        cbbPhong.setToolTipText("PB001( Nhân Sự); \nPB002(Kế Hoạch); \nPB003(Đề Án); \nPB004( Kinh Doanh)"); // NOI18N
        cbbPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbPhongActionPerformed(evt);
            }
        });

        btnThemNV.setText("Thêm nhân viên");
        btnThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNVActionPerformed(evt);
            }
        });

        dateNgaySinh.setDateFormatString("dd/MM/yyyy");

        jLabel11.setText("Phái:");

        javax.swing.GroupLayout pnThemNVLayout = new javax.swing.GroupLayout(pnThemNV);
        pnThemNV.setLayout(pnThemNVLayout);
        pnThemNVLayout.setHorizontalGroup(
            pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfMaNV)
                    .addComponent(cbbPhai, 0, 89, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThemNVLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnThemNVLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnThemNVLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbPhong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnThemNVLayout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbCapBac, 0, 97, Short.MAX_VALUE)
                    .addComponent(tfLuong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnThemNVLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnThemNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnThemNVLayout.setVerticalGroup(
            pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemNVLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(tfMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(3, 3, 3)
                .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbPhai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cbbPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(cbbCapBac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThemNV)))
                .addGap(19, 19, 19))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Phân role"));

        cbbNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "NV101", "NV102", "NV103" }));
        cbbNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNhanVienActionPerformed(evt);
            }
        });

        jLabel10.setText("Chọn nhân viên:");

        listRoleCoSan.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listRoleCoSanValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listRoleCoSan);

        jLabel12.setText("Danh sách role sẳn có:");

        jLabel13.setText("Danh sách role được gán:");

        listRoleDuocCap.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listRoleDuocCapValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listRoleDuocCap);

        btnCapRole.setText(">>");
        btnCapRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapRoleActionPerformed(evt);
            }
        });

        btnThuRole.setText("<<");
        btnThuRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuRoleActionPerformed(evt);
            }
        });

        tableRole.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên bảng", "Sở hữu", "Quyền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableRole);

        jLabel14.setText("Quyền role trên bảng:");

        btnCapNhatNV.setText("Cập nhật NV");
        btnCapNhatNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(cbbNhanVien, 0, 100, Short.MAX_VALUE)
                            .addComponent(btnCapNhatNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCapRole)
                            .addComponent(btnThuRole))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane3)))
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnCapNhatNV))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(btnCapRole)
                            .addGap(40, 40, 40)
                            .addComponent(btnThuRole))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(7, 7, 7)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnScrollLayout = new javax.swing.GroupLayout(pnScroll);
        pnScroll.setLayout(pnScrollLayout);
        pnScrollLayout.setHorizontalGroup(
            pnScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnScrollLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnThemNV, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnScrollLayout.setVerticalGroup(
            pnScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnScrollLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(pnScroll);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHello, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnHello, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void loadUserName()
    {
        DefaultComboBoxModel dcbmodel_NV=new DefaultComboBoxModel();
        dcbmodel_NV.addElement("-----");
        // load các user/nv có mã bắt đầu là NV
        String strGet = "select username from DBA_users where username like 'NV%' order by username";
        try {
            PreparedStatement pstmt = con.prepareStatement(strGet);
            ResultSet rs = pstmt.executeQuery();
            if(rs!=null){
                while (rs.next()) {                    
                    dcbmodel_NV.addElement(rs.getString("username"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        cbbNhanVien.setModel(dcbmodel_NV);
    }
    private void tfHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHoTenActionPerformed

    private void cbbPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbPhongActionPerformed

    private void cbbPhaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbPhaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbPhaiActionPerformed

    private void btnThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNVActionPerformed
        Nhanvien nv= new Nhanvien();
        nv.setMaNV(tfMaNV.getText().toUpperCase());
        nv.setHoTen(tfHoTen.getText());
        nv.setSdt(tfSDT.getText());
        
        
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        String dateFormat = formatter.format(dateNgaySinh.getDate());
        nv.setNgaySinh(dateFormat);
        
        nv.setPhongBan(cbbPhong.getSelectedItem().toString());
        nv.setPhai(cbbPhai.getSelectedItem().toString());
        nv.setLuong(tfLuong.getText());
        nv.setPhuCap(tfPhuCap.getText());
        nv.setCapBac(cbbCapBac.getSelectedItem().toString());
        System.out.println(nv.toString());
        String strGet = "select * from QLDA.NHANVIEN where MANV like ?";
        try {
            PreparedStatement pstmt = con.prepareStatement(strGet);
            pstmt.setString(1, nv.getMaNV());
            ResultSet rs = pstmt.executeQuery();
            if(rs!=null){
                // kiểm tra MANV đã tồn tại
                while (rs.next()) { 
                    JOptionPane.showMessageDialog(null, "MANV đã tồn tại!.","Thông báo",1);
                    tfMaNV.requestFocus();
                    return;
                }
            }
            strGet ="insert into QLDA.NHANVIEN (MANV,HOTEN,PHAI,NGAYSINH,DIENTHOAI,LUONG,PHUCAP,MAPHONG,CAPBAC)VALUES "
                    + "('"+nv.getMaNV()+"','"
                    + nv.getHoTen()+"','"
                    + nv.getPhai()+"',"
                    + "TO_DATE('"+nv.getNgaySinh()+"','DD/MM/YYYY')"+",'"
                    + nv.getSdt()+"','"
                    + nv.getLuong()+"','"
                    + nv.getPhuCap()+"','"
                    + nv.getPhongBan()+"','"
                    + nv.getCapBac()+"')";
            System.out.println(strGet);
            
            pstmt = con.prepareStatement(strGet);
            pstmt.executeUpdate();
            
            strGet="CREATE USER "+nv.getMaNV()+" IDENTIFIED BY "+nv.getMaNV();
            System.out.println(strGet);
            pstmt = con.prepareStatement(strGet);
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Thêm NV thành công, vui lòng cấp role.","Thông báo",1);
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Xảy ra lỗi khi kết nối CSDL.","Thông báo",1);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemNVActionPerformed

    private void cbbNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNhanVienActionPerformed
        // TODO add your handling code here:
        DefaultListModel dlm_RoleCoSan= new DefaultListModel();
        DefaultListModel dlm_RoleDuocCap= new DefaultListModel();
        
        String selectedNV= cbbNhanVien.getSelectedItem().toString();
        if(selectedNV=="-----"){
            listRoleCoSan.setModel(dlm_RoleCoSan);
            listRoleDuocCap.setModel(dlm_RoleDuocCap);
            Vector clums = new Vector();
            clums.add("Tên bảng");
            clums.add("Chủ sở hữu");
            clums.add("Quyền");
            Vector data = new Vector();
            DefaultTableModel dtm_Role = new DefaultTableModel(data, clums);
            tableRole.setModel(dtm_Role);
            return;
        }
        
        
        String strGet = "select ROLE from Dba_roles where ROLE like 'ROLE%' and ROLE not in (select granted_role from Dba_role_privs where grantee like ?)order by ROLE";
        try {
            PreparedStatement pstmt = con.prepareStatement(strGet);
            pstmt.setString(1, selectedNV);
            ResultSet rs = pstmt.executeQuery();
            if(rs!=null){
                while (rs.next()) {                    
                    dlm_RoleCoSan.addElement(rs.getString("ROLE"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        listRoleCoSan.setModel(dlm_RoleCoSan);
        
        
        
        strGet = "select granted_role from Dba_role_privs where grantee like ? order by granted_role";
        try {
            PreparedStatement pstmt = con.prepareStatement(strGet);
            pstmt.setString(1, selectedNV);
            ResultSet rs = pstmt.executeQuery();
            if(rs!=null){
                while (rs.next()) {                    
                    dlm_RoleDuocCap.addElement(rs.getString("granted_role"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        listRoleDuocCap.setModel(dlm_RoleDuocCap);
    }//GEN-LAST:event_cbbNhanVienActionPerformed

    private void listRoleCoSanValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listRoleCoSanValueChanged
        // TODO add your handling code here:
        
        Vector clums = new Vector();
        clums.add("Tên bảng");
        clums.add("Chủ sở hữu");
        clums.add("Quyền");
        Vector data = new Vector();
        
        String strGet;
        String value = listRoleCoSan.getSelectedValue();
        if(value != null)
        {
            
            strGet = "SELECT TABLE_NAME,OWNER,PRIVILEGE FROM ROLE_TAB_PRIVS WHERE ROLE LIKE ? ORDER BY TABLE_NAME";
            try {
                PreparedStatement pstmt = con.prepareStatement(strGet);
                pstmt.setString(1, value);
                ResultSet rs = pstmt.executeQuery();
                if(rs!=null){
                    while (rs.next()) {                    
                        Vector row = new Vector();
                        row.add(rs.getString(1));
                        row.add(rs.getString(2));
                        row.add(rs.getString(3));
                        data.add(row);
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            DefaultTableModel dtm_Role= new DefaultTableModel(data, clums);
            tableRole.setModel(dtm_Role);
        }
    }//GEN-LAST:event_listRoleCoSanValueChanged

    private void listRoleDuocCapValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listRoleDuocCapValueChanged
        // TODO add your handling code here:
        Vector clums = new Vector();
        clums.add("Tên bảng");
        clums.add("Chủ sở hữu");
        clums.add("Quyền");
        Vector data = new Vector();
        
        String strGet;
        String value= listRoleDuocCap.getSelectedValue();
        if(value != null)
        {
            
            strGet = "select table_name,owner,privilege from Role_tab_privs where role like ? order by table_name";
            try {
                PreparedStatement pstmt = con.prepareStatement(strGet);
                pstmt.setString(1, value);
                ResultSet rs = pstmt.executeQuery();
                if(rs!=null){
                    while (rs.next()) {                    
                        Vector row = new Vector();
                        row.add(rs.getString("table_name"));
                        row.add(rs.getString("owner"));
                        row.add(rs.getString("privilege"));
                        data.add(row);
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            DefaultTableModel dtm_Role= new DefaultTableModel(data, clums);
            tableRole.setModel(dtm_Role);
        }
    }//GEN-LAST:event_listRoleDuocCapValueChanged

    private void btnCapRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapRoleActionPerformed
        // TODO add your handling code here:
        String value=listRoleCoSan.getSelectedValue();
        String username=cbbNhanVien.getSelectedItem().toString();
        if(value !=null && username !=null)
        {
            int index=listRoleCoSan.getSelectedIndex();
            
            DefaultListModel model1 = (DefaultListModel) listRoleCoSan.getModel();
            model1.remove(index);
            listRoleCoSan.setModel(model1);
            
            // gọi oracle cấp role
            String strGet = "grant " + value + " to " + username;
            try {
                // cấp role
                System.out.println(strGet);
                PreparedStatement pstmt = con.prepareStatement(strGet);
                ResultSet rs = pstmt.executeQuery();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Xảy ra lỗi truy vấn CSDL, vui lòng thử lại","Thông báo",1);
                e.printStackTrace();
                return;
            }
            
            DefaultListModel model2 = (DefaultListModel) listRoleDuocCap.getModel();
            model2.addElement(value);
            listRoleDuocCap.setModel(model2);
            
            JOptionPane.showMessageDialog(null, "Cấp role thành công","Thông báo",1);
        }
    }//GEN-LAST:event_btnCapRoleActionPerformed

    private void btnThuRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuRoleActionPerformed
        // TODO add your handling code here:
        String value=listRoleDuocCap.getSelectedValue();
        String username=cbbNhanVien.getSelectedItem().toString();
        if(value !=null && username!=null)
        {
            int index=listRoleDuocCap.getSelectedIndex();
            DefaultListModel model1 = (DefaultListModel) listRoleDuocCap.getModel();
            model1.remove(index);
            listRoleDuocCap.setModel(model1);
            
            // gọi oracle thu role
            String strGet = "revoke " + value + " from " + username;
            try {
                // thu ROLE đã cấp
                System.out.println(strGet);
                PreparedStatement pstmt = con.prepareStatement(strGet);
                ResultSet rs = pstmt.executeQuery();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Xảy ra lỗi truy vấn CSDL, vui lòng thử lại","Thông báo",1);
                e.printStackTrace();
                return;
            }
            
            DefaultListModel model2 = (DefaultListModel) listRoleCoSan.getModel();
            model2.addElement(value);
            listRoleCoSan.setModel(model2);
            
            JOptionPane.showMessageDialog(null, "Thu hồi role thành công","Thông báo",1);
        }
    }//GEN-LAST:event_btnThuRoleActionPerformed

    private void tfLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLuongActionPerformed

    private void btnCapNhatNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatNVActionPerformed
        // TODO add your handling code here:
        loadUserName();
    }//GEN-LAST:event_btnCapNhatNVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatNV;
    private javax.swing.JButton btnCapRole;
    private javax.swing.JButton btnThemNV;
    private javax.swing.JButton btnThuRole;
    private javax.swing.JComboBox<String> cbbCapBac;
    private javax.swing.JComboBox<String> cbbNhanVien;
    private javax.swing.JComboBox<String> cbbPhai;
    private javax.swing.JComboBox<String> cbbPhong;
    private com.toedter.calendar.JDateChooser dateNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listRoleCoSan;
    private javax.swing.JList<String> listRoleDuocCap;
    private javax.swing.JPanel pnHello;
    private javax.swing.JPanel pnScroll;
    private javax.swing.JPanel pnThemNV;
    private javax.swing.JTable tableRole;
    private javax.swing.JTextField tfHoTen;
    private javax.swing.JTextField tfLuong;
    private javax.swing.JTextField tfMaNV;
    private javax.swing.JTextField tfPhuCap;
    private javax.swing.JTextField tfSDT;
    // End of variables declaration//GEN-END:variables
}
